name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
      name: Uploading
      uses: actions/upload-artifact@v2
      if: always()
      with: 
        name: cypress-execution-report
        path: cypress/reports/html
        retention-days: 30